### ISSUE TITLE
Can C.Origami predict the 3D chromatin with out CTCF ChIP-seq input data?

### ISSUE THREAD

**Issue by YCMaCY** [tanjimin/C.Origami#26]
I  have the cut&tag data for CTCF, but no corresponding input data. Can I just use ip data to predict the architecture?

**Comment by tanjimin** [comment]
Hi @YCMaCY. Yes you can do it in different ways. The best way is to re-train with CTCF IP and use the new model. Another way is to create a pseudo CTCF input by averaging CTCF IP and then calculate with log2fc, so that it is compatible with pre-trained model. I haven't tried this, so I am also curious if it could work.

**Comment by tanjimin** [comment]
Hi @YCMaCY. Yes you can do it in two ways. 
1. The preferred way is to re-train with CTCF IP and use the new model. 
2. Without retraining, we can create a pseudo CTCF input by averaging CTCF IP and then compute log2fc which is compatible with the pre-trained model. I haven't tried this, so let me know if it works.

**Comment by YCMaCY** [comment]
Thank you for your great suggestion！

**Comment by alkurowska** [comment]
In my data, I only have RNA-seq, ATAC-seq and H3K27ac ChIP-seq. Is it something that I can try to use Origami with?

**Comment by tanjimin** [comment]
> In my data, I only have RNA-seq, ATAC-seq and H3K27ac ChIP-seq. Is it something that I can try to use Origami with?
> 
> 

Hi @alkurowska you probably need to retrain the model. You can try replacing CTCF with H3K27ac and see if it works. If you want to do this, check the training section in README and the dataloader code.
