### ISSUE TITLE
`examples/prediction.sh` generates blank Hi-C image for chromosome 15

### ISSUE THREAD

**Issue by My-laniaKeA** [tanjimin/C.Origami#28]
Hi @tanjimin,

First of all, thanks for sharing your work in this repo.

I was trying to run the example provided in `examples/prediction.sh`, but it did not give the expected result. To be more specific, I modified the chromosome to `--chr "chr15"`, and the rest is consistent with the documentation. The output Hi-C image is blank, while the numpy array looks fine. The output image remains blank for other start positions as well.

Can you please look into this problem? Thank you.

**Comment by tanjimin** [comment]
Hi @My-laniaKeA,I believe the beginning of some chromosomes are unmappable regions. (E.g. chr13, 14 and 15). So it might due to the data itself. If you check CTCF and ATAC-seq there should be no signals. You can either look at regions further into chr15 or other chromosomes and see if the issue persist.

**Comment by My-laniaKeA** [comment]
Thank you for your solution. I looked into other regions and chromosomes, and got the expected output.
