### ISSUE TITLE
Questions about performance comparison with deepC

### ISSUE THREAD

**Issue by My-laniaKeA** [tanjimin/C.Origami#30]
I am interested in the performance comparison with deepC. Could you please provide more details about training deepC with IMR-90 data? For example:

- Did you use hg19 or hg38 as the reference genome?
- DeepC has 2 training phases. Did you re-train the model for both phases?
- If you perform the training for phase I, what chromatin features were selected? 

I'm looking forward to your response.

**Comment by tanjimin** [comment]
Hi @My-laniaKeA Thank you for the comment. For all previous models, we used their released model weights and did not re-train those models from scratch. I assume the previous models are trained on hg19 but it did not matter because  trained models should generalize across different assemblies.

The trained models for DeepC can be found here: https://github.com/rschwess/deepC/tree/master/models. I used their IMR-90 trained model.

**Comment by My-laniaKeA** [comment]
Thank you for clarifying these details. It really helped me understand the great work better.
